# This workflow will test anaconda login

name: Login to Anaconda

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: build_and_publish
    steps:
    - name: Install anaconda
      run: conda install anaconda 
    - name: Build and publish on Anaconda
      env:
        ANCONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME }}
        ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
      run: |
        anaconda login --username $ANCONDA_USERNAME --password $ANACONDA_PASSWORD
