# This workflow will test anaconda login

name: Login to Anaconda

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: build_and_publish
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Check installation
      run: |
        cd /usr/share/miniconda/bin
        ls
    - name: Install anaconda
      run: conda install anaconda-client
    - name: Insstall anaconda from npm
      run: npm install -g anaconda
    - name: Login to Anaconda
      env:
        ANCONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME }}
        ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
      run: |
        anaconda login --username $ANCONDA_USERNAME --password $ANACONDA_PASSWORD
