# This workflow will reformat all python files with yapf

name: CI-test

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          mamba-version: "*"
#          activate-environment: test
#          environment-file: environment.yml
#          auto-activate-base: false
#          auto-update-conda: true
#          python-version: ${{ matrix.python-version }}
      - name: Set up Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'
      - name: Install dependencies
        run: |
          micromamba install flake8 wheel pytest setuptools
#          python -m pip install --upgrade pip
#          pip install flake8 wheel pytest setuptools
      - name: Install solvers
        run: |
         micromamba install -c conda-forge pyscipopt scip -c ibmdecisionoptimization cplex -c gurobi gurobi
#          pip install cplex gurobipy
#          mamba install -c conda-forge pyscipopt scip=8.0.0
      - name: Install straindesign
        run: | 
          pip install -e .
      - name: Test with pytest
        run: pytest tests
        
