name: Build and Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install pyscipopt
        run: conda install -c conda-forge pyscipopt
      - name: List stuff
        run: |
          conda info
          conda env list
          conda list        
      - name: Import pyscipopt
        run: python -c "import pyscipopt"
