# This workflow will upload a Python Package using Twine when a release is created

name: Build and Upload Python Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
      header:
        description: 'Header'
        required: true
      description:
        description: 'Description'
        required: false

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: build_and_publish
    steps:
    - uses: actions/checkout@v3
    - name: Print version number
      run: echo ${{ github.event.inputs.version }}
    - name: Update version number
      run: |
        python ./.github/update_version.py setup.py ${{ github.event.inputs.version }}
        python ./.github/update_version.py conda-recipe/meta.yaml ${{ github.event.inputs.version }}
    - name: Name and E-Mail configuration
      run: |
        git config --global user.name ${{ secrets.NAME_GITHUB }}
        git config --global user.email ${{ secrets.MAIL_GITHUB }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Updated version number"
    - name: fetch
      run: git fetch
    - name: push code to main
      run: git push
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: v${{ github.event.inputs.version }}
        tag_name: v${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.header }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel twine anaconda-client conda-build
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        ANCONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME }}
        ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
      run: |
        rm -rf dist
        rm -rf conda-bld
        python setup.py sdist bdist_wheel
        twine upload dist/*
        mkdir conda-bld
        conda-build conda-recipe/. -c conda-forge --croot conda-bld
        anaconda login --username $ANCONDA_USERNAME --password $ANACONDA_PASSWORD
        anaconda upload -u cnapy conda-bld/noarch/straindesign*
        rm -rf dist
        rm -rf conda-bld
