# This workflow will reformat all python files with yapf

name: Reformat with yapf

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: build_and_publish
    steps:
    - uses: actions/checkout@v3
    - name: Install yapf dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yapf 
    - name: Python formatting
      run: yapf -i -r --style google .
    - name: Name and E-Mail configuration
      run: |
        git config --global user.name ${{ secrets.NAME_GITHUB }}
        git config --global user.email ${{ secrets.MAIL_GITHUB }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git diff
    - name: Check yapf
      run: yapf -d -r .
